{
 "title": "products",
 "tags": [ "go" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Base",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of instances",
     "type": "singlestat",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(up{app=\"products\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Go",
   "type": "row",
   "collapsed": true,
   "panels": [
    {
     "title": "go_goroutines",
     "type": "graph",
     "description": "Number of goroutines that currently exist",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{app=\"products\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_alloc_bytes",
     "type": "graph",
     "description": "Number of bytes allocated and still in use",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{app=\"products\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_alloc_bytes_total",
     "type": "graph",
     "description": "Total number of bytes allocated, even if freed",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes_total{app=\"products\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_buck_hash_sys_bytes",
     "type": "graph",
     "description": "Number of bytes used by the profiling bucket hash table",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "go_memstats_buck_hash_sys_bytes{app=\"products\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_frees_total",
     "type": "graph",
     "description": "Total number of frees",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "go_memstats_frees_total{app=\"products\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_gc_cpu_fraction",
     "type": "graph",
     "description": "The fraction of this program's available CPU time used by the GC since the program started.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "go_memstats_gc_cpu_fraction{app=\"products\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_gc_sys_bytes",
     "type": "graph",
     "description": "Number of bytes used for garbage collection system metadata",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "go_memstats_gc_sys_bytes{app=\"products\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_heap_alloc_bytes",
     "type": "graph",
     "description": "Number of heap bytes allocated and still in use",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{app=\"products\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_heap_idle_bytes",
     "type": "graph",
     "description": "Number of heap bytes waiting to be used",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_idle_bytes{app=\"products\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_heap_inuse_bytes",
     "type": "graph",
     "description": "Number of heap bytes that are in use",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_inuse_bytes{app=\"products\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_heap_objects",
     "type": "graph",
     "description": "Number of allocated objects",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_objects{app=\"products\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_heap_released_bytes",
     "type": "graph",
     "description": "Number of heap bytes released to OS",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_released_bytes{app=\"products\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_heap_sys_bytes",
     "type": "graph",
     "description": "Number of heap bytes obtained from system",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_sys_bytes{app=\"products\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_last_gc_time_seconds",
     "type": "graph",
     "description": "Number of seconds since 1970 of last garbage collection",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "go_memstats_last_gc_time_seconds{app=\"products\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_lookups_total",
     "type": "graph",
     "description": "Total number of pointer lookups",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "go_memstats_lookups_total{app=\"products\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_mallocs_total",
     "type": "graph",
     "description": "Total number of mallocs",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mallocs_total{app=\"products\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_mcache_inuse_bytes",
     "type": "graph",
     "description": "Number of bytes in use by mcache structures",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mcache_inuse_bytes{app=\"products\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_mcache_sys_bytes",
     "type": "graph",
     "description": "Number of bytes used for mcache structures obtained from system",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mcache_sys_bytes{app=\"products\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_mspan_inuse_bytes",
     "type": "graph",
     "description": "Number of bytes in use by mspan structures",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mspan_inuse_bytes{app=\"products\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_mspan_sys_bytes",
     "type": "graph",
     "description": "Number of bytes used for mspan structures obtained from system",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mspan_sys_bytes{app=\"products\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_next_gc_bytes",
     "type": "graph",
     "description": "Number of heap bytes when next garbage collection will take place",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "go_memstats_next_gc_bytes{app=\"products\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_other_sys_bytes",
     "type": "graph",
     "description": "Number of bytes used for other system allocations",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "go_memstats_other_sys_bytes{app=\"products\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_stack_inuse_bytes",
     "type": "graph",
     "description": "Number of bytes in use by the stack allocator",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "go_memstats_stack_inuse_bytes{app=\"products\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_stack_sys_bytes",
     "type": "graph",
     "description": "Number of bytes obtained from system for stack allocator",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "go_memstats_stack_sys_bytes{app=\"products\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_sys_bytes",
     "type": "graph",
     "description": "Number of bytes obtained from system",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "go_memstats_sys_bytes{app=\"products\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Grpc",
   "type": "row",
   "collapsed": true,
   "panels": [
    {
     "title": "Grpc server QPS by grpc_code",
     "type": "graph",
     "description": "Number of grpc server request group by grpc_code per seconds",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "format": "none",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{app=\"products\",grpc_type=\"unary\"}[1m])) by (grpc_code)",
       "legendFormat": "{{grpc_code}}"
      }
     ]
    },
    {
     "title": "Grpc server QPS by instance",
     "type": "graph",
     "description": "Number of grpc server request group by instance per seconds",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "format": "none",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{app=\"products\",grpc_type=\"unary\"}[1m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Grpc server QPS by grpc_service",
     "type": "graph",
     "description": "Number of grpc server request group by grpc_service per seconds",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "format": "none",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{app=\"products\",grpc_type=\"unary\"}[1m])) by (grpc_service)",
       "legendFormat": "{{grpc_service}}"
      }
     ]
    },
    {
     "title": "Grpc server QPS by grpc_service,grpc_method",
     "type": "graph",
     "description": "Number of grpc server request group by grpc_service,grpc_method per seconds",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "format": "none",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{app=\"products\",grpc_type=\"unary\"}[1m])) by (grpc_service,grpc_method)",
       "legendFormat": "{{grpc_service}}.{{grpc_method}}"
      }
     ]
    }
   ]
  }
 ]
}