{
 "title": "reviews",
 "tags": [ "go" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Base",
   "type": "row",
   "collapsed": true,
   "panels": [
    {
     "title": "Number of instances",
     "type": "singlestat",
     "gridPos": { "h": 10, "w": 4, "x": 0, "y": 0 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(up{app=\"reviews\"})"
      }
     ]
    },
    {
     "title": "Number of grpc request  per seconds",
     "type": "singlestat",
     "gridPos": { "h": 10, "w": 4, "x": 4, "y": 0 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{app=\"reviews\",grpc_type=\"unary\"}[1m]))"
      }
     ]
    },
    {
     "title": "Percentage of grpc error request",
     "type": "singlestat",
     "gridPos": { "h": 10, "w": 4, "x": 8, "y": 0 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{app=\"reviews\",grpc_type=\"unary\",grpc_code!=\"OK\"}[1m])) /sum(rate(grpc_server_started_total{app=\"reviews\",grpc_type=\"unary\"}[1m])) * 100.0"
      }
     ]
    },
    {
     "title": "Number of http request  per seconds",
     "type": "singlestat",
     "gridPos": { "h": 10, "w": 4, "x": 12, "y": 0 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{app=\"reviews\"}[1m]))"
      }
     ]
    },
    {
     "title": "Percentage of http error request",
     "type": "singlestat",
     "gridPos": { "h": 10, "w": 4, "x": 16, "y": 0 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{app=\"reviews\",status!=\"200\"}[1m])) /sum(rate(http_server_requests_seconds_count{app=\"reviews\"}[1m])) * 100.0"
      }
     ]
    }
   ]
  },
  {
   "title": "Go",
   "type": "row",
   "collapsed": true,
   "panels": [
    {
     "title": "go_goroutines",
     "type": "graph",
     "description": "Number of goroutines that currently exist",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{app=\"reviews\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_alloc_bytes",
     "type": "graph",
     "description": "Number of bytes allocated and still in use",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{app=\"reviews\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_alloc_bytes_total",
     "type": "graph",
     "description": "Total number of bytes allocated, even if freed",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes_total{app=\"reviews\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_buck_hash_sys_bytes",
     "type": "graph",
     "description": "Number of bytes used by the profiling bucket hash table",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_buck_hash_sys_bytes{app=\"reviews\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_frees_total",
     "type": "graph",
     "description": "Total number of frees",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_frees_total{app=\"reviews\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_gc_cpu_fraction",
     "type": "graph",
     "description": "The fraction of this program's available CPU time used by the GC since the program started.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_gc_cpu_fraction{app=\"reviews\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_gc_sys_bytes",
     "type": "graph",
     "description": "Number of bytes used for garbage collection system metadata",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_gc_sys_bytes{app=\"reviews\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_heap_alloc_bytes",
     "type": "graph",
     "description": "Number of heap bytes allocated and still in use",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{app=\"reviews\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_heap_idle_bytes",
     "type": "graph",
     "description": "Number of heap bytes waiting to be used",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_idle_bytes{app=\"reviews\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_heap_inuse_bytes",
     "type": "graph",
     "description": "Number of heap bytes that are in use",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_inuse_bytes{app=\"reviews\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_heap_objects",
     "type": "graph",
     "description": "Number of allocated objects",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_objects{app=\"reviews\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_heap_released_bytes",
     "type": "graph",
     "description": "Number of heap bytes released to OS",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_released_bytes{app=\"reviews\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_heap_sys_bytes",
     "type": "graph",
     "description": "Number of heap bytes obtained from system",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_sys_bytes{app=\"reviews\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_last_gc_time_seconds",
     "type": "graph",
     "description": "Number of seconds since 1970 of last garbage collection",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_last_gc_time_seconds{app=\"reviews\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_lookups_total",
     "type": "graph",
     "description": "Total number of pointer lookups",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_lookups_total{app=\"reviews\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_mallocs_total",
     "type": "graph",
     "description": "Total number of mallocs",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mallocs_total{app=\"reviews\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_mcache_inuse_bytes",
     "type": "graph",
     "description": "Number of bytes in use by mcache structures",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mcache_inuse_bytes{app=\"reviews\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_mcache_sys_bytes",
     "type": "graph",
     "description": "Number of bytes used for mcache structures obtained from system",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mcache_sys_bytes{app=\"reviews\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_mspan_inuse_bytes",
     "type": "graph",
     "description": "Number of bytes in use by mspan structures",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mspan_inuse_bytes{app=\"reviews\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_mspan_sys_bytes",
     "type": "graph",
     "description": "Number of bytes used for mspan structures obtained from system",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mspan_sys_bytes{app=\"reviews\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_next_gc_bytes",
     "type": "graph",
     "description": "Number of heap bytes when next garbage collection will take place",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_next_gc_bytes{app=\"reviews\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_other_sys_bytes",
     "type": "graph",
     "description": "Number of bytes used for other system allocations",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_other_sys_bytes{app=\"reviews\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_stack_inuse_bytes",
     "type": "graph",
     "description": "Number of bytes in use by the stack allocator",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_stack_inuse_bytes{app=\"reviews\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_stack_sys_bytes",
     "type": "graph",
     "description": "Number of bytes obtained from system for stack allocator",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_stack_sys_bytes{app=\"reviews\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go_memstats_sys_bytes",
     "type": "graph",
     "description": "Number of bytes obtained from system",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_sys_bytes{app=\"reviews\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Grpc Server request rate",
   "type": "row",
   "collapsed": true,
   "panels": [
    {
     "title": "Number of grpc server request  per seconds group by (grpc_code)",
     "type": "graph",
     "description": "Number of grpc server request per seconds  group by (grpc_code)",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{app=\"reviews\",grpc_type=\"unary\"}[1m])) by (grpc_code)",
       "legendFormat": "{{grpc_code}}"
      }
     ]
    },
    {
     "title": "Number of grpc server request  per seconds group by (instance)",
     "type": "graph",
     "description": "Number of grpc server request per seconds  group by (instance)",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{app=\"reviews\",grpc_type=\"unary\"}[1m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Number of grpc server request  per seconds group by (grpc_service)",
     "type": "graph",
     "description": "Number of grpc server request per seconds  group by (grpc_service)",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{app=\"reviews\",grpc_type=\"unary\"}[1m])) by (grpc_service)",
       "legendFormat": "{{grpc_service}}"
      }
     ]
    },
    {
     "title": "Number of grpc server request  per seconds group by (grpc_service,grpc_method)",
     "type": "graph",
     "description": "Number of grpc server request per seconds  group by (grpc_service,grpc_method)",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{app=\"reviews\",grpc_type=\"unary\"}[1m])) by (grpc_service,grpc_method)",
       "legendFormat": "{{grpc_service}}.{{grpc_method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Grpc Server request error percentage",
   "type": "row",
   "collapsed": true,
   "panels": [
    {
     "title": "Percentage of grpc server error request group by (grpc_code)",
     "type": "graph",
     "description": "Percentage of grpc server error request group by (grpc_code)",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{app=\"reviews\",grpc_type=\"unary\",grpc_code!=\"OK\"}[1m])) by (grpc_code)/sum(rate(grpc_server_started_total{app=\"reviews\",grpc_type=\"unary\"}[1m])) by (grpc_code)* 100.0",
       "legendFormat": "{{grpc_code}}"
      }
     ]
    },
    {
     "title": "Percentage of grpc server error request group by (instance)",
     "type": "graph",
     "description": "Percentage of grpc server error request group by (instance)",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{app=\"reviews\",grpc_type=\"unary\",grpc_code!=\"OK\"}[1m])) by (instance)/sum(rate(grpc_server_started_total{app=\"reviews\",grpc_type=\"unary\"}[1m])) by (instance)* 100.0",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Percentage of grpc server error request group by (grpc_service)",
     "type": "graph",
     "description": "Percentage of grpc server error request group by (grpc_service)",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{app=\"reviews\",grpc_type=\"unary\",grpc_code!=\"OK\"}[1m])) by (grpc_service)/sum(rate(grpc_server_started_total{app=\"reviews\",grpc_type=\"unary\"}[1m])) by (grpc_service)* 100.0",
       "legendFormat": "{{grpc_service}}"
      }
     ]
    },
    {
     "title": "Percentage of grpc server error request group by (grpc_service,grpc_method)",
     "type": "graph",
     "description": "Percentage of grpc server error request group by (grpc_service,grpc_method)",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{app=\"reviews\",grpc_type=\"unary\",grpc_code!=\"OK\"}[1m])) by (grpc_service,grpc_method)/sum(rate(grpc_server_started_total{app=\"reviews\",grpc_type=\"unary\"}[1m])) by (grpc_service,grpc_method)* 100.0",
       "legendFormat": "{{grpc_service}}.{{grpc_method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Grpc server 99%-tile Latency of requests",
   "type": "row",
   "collapsed": true,
   "panels": [
    {
     "title": "Latency of grpc server request group by (grpc_code)",
     "type": "graph",
     "description": "Latency of grpc server request group by (grpc_code)",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "1000 * histogram_quantile(0.98999999999999999,sum(rate(grpc_server_handling_seconds_bucket{app=\"reviews\",grpc_type=\"unary\"}[1m])) by (grpc_code,le))",
       "legendFormat": "{{grpc_code}}"
      }
     ]
    },
    {
     "title": "Latency of grpc server request group by (instance)",
     "type": "graph",
     "description": "Latency of grpc server request group by (instance)",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "1000 * histogram_quantile(0.98999999999999999,sum(rate(grpc_server_handling_seconds_bucket{app=\"reviews\",grpc_type=\"unary\"}[1m])) by (instance,le))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Latency of grpc server request group by (grpc_service)",
     "type": "graph",
     "description": "Latency of grpc server request group by (grpc_service)",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "1000 * histogram_quantile(0.98999999999999999,sum(rate(grpc_server_handling_seconds_bucket{app=\"reviews\",grpc_type=\"unary\"}[1m])) by (grpc_service,le))",
       "legendFormat": "{{grpc_service}}"
      }
     ]
    },
    {
     "title": "Latency of grpc server request group by (grpc_service,grpc_method)",
     "type": "graph",
     "description": "Latency of grpc server request group by (grpc_service,grpc_method)",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "1000 * histogram_quantile(0.98999999999999999,sum(rate(grpc_server_handling_seconds_bucket{app=\"reviews\",grpc_type=\"unary\"}[1m])) by (grpc_service,grpc_method,le))",
       "legendFormat": "{{grpc_service}}.{{grpc_method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Grpc client request rate",
   "type": "row",
   "collapsed": true,
   "panels": [
    {
     "title": "Number of grpc client request  per seconds group by (grpc_code)",
     "type": "graph",
     "description": "Number of grpc client request per seconds  group by (grpc_code)",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_client_handled_total{app=\"reviews\",grpc_type=\"unary\"}[1m])) by (grpc_code)",
       "legendFormat": "{{grpc_code}}"
      }
     ]
    },
    {
     "title": "Number of grpc client request  per seconds group by (instance)",
     "type": "graph",
     "description": "Number of grpc client request per seconds  group by (instance)",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_client_handled_total{app=\"reviews\",grpc_type=\"unary\"}[1m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Number of grpc client request  per seconds group by (grpc_service)",
     "type": "graph",
     "description": "Number of grpc client request per seconds  group by (grpc_service)",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_client_handled_total{app=\"reviews\",grpc_type=\"unary\"}[1m])) by (grpc_service)",
       "legendFormat": "{{grpc_service}}"
      }
     ]
    },
    {
     "title": "Number of grpc client request  per seconds group by (grpc_service,grpc_method)",
     "type": "graph",
     "description": "Number of grpc client request per seconds  group by (grpc_service,grpc_method)",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_client_handled_total{app=\"reviews\",grpc_type=\"unary\"}[1m])) by (grpc_service,grpc_method)",
       "legendFormat": "{{grpc_service}}.{{grpc_method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Grpc client request error percentage",
   "type": "row",
   "collapsed": true,
   "panels": [
    {
     "title": "Percentage of grpc client error request group by (grpc_code)",
     "type": "graph",
     "description": "Percentage of grpc client error request group by (grpc_code)",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_client_handled_total{app=\"reviews\",grpc_type=\"unary\",grpc_code!=\"OK\"}[1m])) by (grpc_code)/sum(rate(grpc_client_started_total{app=\"reviews\",grpc_type=\"unary\"}[1m])) by (grpc_code)* 100.0",
       "legendFormat": "{{grpc_code}}"
      }
     ]
    },
    {
     "title": "Percentage of grpc client error request group by (instance)",
     "type": "graph",
     "description": "Percentage of grpc client error request group by (instance)",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_client_handled_total{app=\"reviews\",grpc_type=\"unary\",grpc_code!=\"OK\"}[1m])) by (instance)/sum(rate(grpc_client_started_total{app=\"reviews\",grpc_type=\"unary\"}[1m])) by (instance)* 100.0",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Percentage of grpc client error request group by (grpc_service)",
     "type": "graph",
     "description": "Percentage of grpc client error request group by (grpc_service)",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_client_handled_total{app=\"reviews\",grpc_type=\"unary\",grpc_code!=\"OK\"}[1m])) by (grpc_service)/sum(rate(grpc_client_started_total{app=\"reviews\",grpc_type=\"unary\"}[1m])) by (grpc_service)* 100.0",
       "legendFormat": "{{grpc_service}}"
      }
     ]
    },
    {
     "title": "Percentage of grpc client error request group by (grpc_service,grpc_method)",
     "type": "graph",
     "description": "Percentage of grpc client error request group by (grpc_service,grpc_method)",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_client_handled_total{app=\"reviews\",grpc_type=\"unary\",grpc_code!=\"OK\"}[1m])) by (grpc_service,grpc_method)/sum(rate(grpc_client_started_total{app=\"reviews\",grpc_type=\"unary\"}[1m])) by (grpc_service,grpc_method)* 100.0",
       "legendFormat": "{{grpc_service}}.{{grpc_method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Grpc client 99%-tile Latency of requests",
   "type": "row",
   "collapsed": true,
   "panels": [
    {
     "title": "Latency of grpc client request group by (grpc_code)",
     "type": "graph",
     "description": "Latency of grpc client request group by (grpc_code)",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "1000 * histogram_quantile(0.98999999999999999,sum(rate(grpc_client_handling_seconds_bucket{app=\"reviews\",grpc_type=\"unary\"}[1m])) by (grpc_code,le))",
       "legendFormat": "{{grpc_code}}"
      }
     ]
    },
    {
     "title": "Latency of grpc client request group by (instance)",
     "type": "graph",
     "description": "Latency of grpc client request group by (instance)",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "1000 * histogram_quantile(0.98999999999999999,sum(rate(grpc_client_handling_seconds_bucket{app=\"reviews\",grpc_type=\"unary\"}[1m])) by (instance,le))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Latency of grpc client request group by (grpc_service)",
     "type": "graph",
     "description": "Latency of grpc client request group by (grpc_service)",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "1000 * histogram_quantile(0.98999999999999999,sum(rate(grpc_client_handling_seconds_bucket{app=\"reviews\",grpc_type=\"unary\"}[1m])) by (grpc_service,le))",
       "legendFormat": "{{grpc_service}}"
      }
     ]
    },
    {
     "title": "Latency of grpc client request group by (grpc_service,grpc_method)",
     "type": "graph",
     "description": "Latency of grpc client request group by (grpc_service,grpc_method)",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "1000 * histogram_quantile(0.98999999999999999,sum(rate(grpc_client_handling_seconds_bucket{app=\"reviews\",grpc_type=\"unary\"}[1m])) by (grpc_service,grpc_method,le))",
       "legendFormat": "{{grpc_service}}.{{grpc_method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Grpc client 90%-tile Latency of requests",
   "type": "row",
   "collapsed": true,
   "panels": [
    {
     "title": "Latency of grpc client request group by (grpc_code)",
     "type": "graph",
     "description": "Latency of grpc client request group by (grpc_code)",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "1000 * histogram_quantile(0.90000000000000002,sum(rate(grpc_client_handling_seconds_bucket{app=\"reviews\",grpc_type=\"unary\"}[1m])) by (grpc_code,le))",
       "legendFormat": "{{grpc_code}}"
      }
     ]
    },
    {
     "title": "Latency of grpc client request group by (instance)",
     "type": "graph",
     "description": "Latency of grpc client request group by (instance)",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "1000 * histogram_quantile(0.90000000000000002,sum(rate(grpc_client_handling_seconds_bucket{app=\"reviews\",grpc_type=\"unary\"}[1m])) by (instance,le))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Latency of grpc client request group by (grpc_service)",
     "type": "graph",
     "description": "Latency of grpc client request group by (grpc_service)",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "1000 * histogram_quantile(0.90000000000000002,sum(rate(grpc_client_handling_seconds_bucket{app=\"reviews\",grpc_type=\"unary\"}[1m])) by (grpc_service,le))",
       "legendFormat": "{{grpc_service}}"
      }
     ]
    },
    {
     "title": "Latency of grpc client request group by (grpc_service,grpc_method)",
     "type": "graph",
     "description": "Latency of grpc client request group by (grpc_service,grpc_method)",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "1000 * histogram_quantile(0.98999999999999999,sum(rate(grpc_client_handling_seconds_bucket{app=\"reviews\",grpc_type=\"unary\"}[1m])) by (grpc_service,grpc_method,le))",
       "legendFormat": "{{grpc_service}}.{{grpc_method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Http server request rate",
   "type": "row",
   "collapsed": true,
   "panels": [
    {
     "title": "Number of http[\"grpc_code\"] request group by (grpc_code) per seconds",
     "type": "graph",
     "description": "Number of http[\"grpc_code\"] request group by (grpc_code) per seconds",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{app=\"reviews\"}[1m])) by (grpc_code)",
       "legendFormat": "{{grpc_code}}"
      }
     ]
    },
    {
     "title": "Number of http[\"instance\"] request group by (grpc_code) per seconds",
     "type": "graph",
     "description": "Number of http[\"instance\"] request group by (grpc_code) per seconds",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{app=\"reviews\"}[1m])) by (grpc_code)",
       "legendFormat": "{{grpc_code}}"
      }
     ]
    },
    {
     "title": "Number of http[\"grpc_service\"] request group by (grpc_code) per seconds",
     "type": "graph",
     "description": "Number of http[\"grpc_service\"] request group by (grpc_code) per seconds",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{app=\"reviews\"}[1m])) by (grpc_code)",
       "legendFormat": "{{grpc_code}}"
      }
     ]
    },
    {
     "title": "Number of http[\"grpc_service\", \"grpc_method\"] request group by (grpc_code) per seconds",
     "type": "graph",
     "description": "Number of http[\"grpc_service\", \"grpc_method\"] request group by (grpc_code) per seconds",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{app=\"reviews\"}[1m])) by (grpc_code)",
       "legendFormat": "{{grpc_code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Http server request error percentage",
   "type": "row",
   "collapsed": true,
   "panels": [
    {
     "title": "Percentage of http error request group by (grpc_code) ",
     "type": "graph",
     "description": "Percentage of http error request group by (grpc_code)",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{app=\"reviews\",status!=\"200\"}[1m])) by (grpc_code)/sum(rate(http_server_requests_seconds_count{app=\"reviews\"}[1m])) by (grpc_code)* 100.0",
       "legendFormat": "{{grpc_code}}"
      }
     ]
    },
    {
     "title": "Percentage of http error request group by (instance) ",
     "type": "graph",
     "description": "Percentage of http error request group by (instance)",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{app=\"reviews\",status!=\"200\"}[1m])) by (instance)/sum(rate(http_server_requests_seconds_count{app=\"reviews\"}[1m])) by (instance)* 100.0",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Percentage of http error request group by (grpc_service) ",
     "type": "graph",
     "description": "Percentage of http error request group by (grpc_service)",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{app=\"reviews\",status!=\"200\"}[1m])) by (grpc_service)/sum(rate(http_server_requests_seconds_count{app=\"reviews\"}[1m])) by (grpc_service)* 100.0",
       "legendFormat": "{{grpc_service}}"
      }
     ]
    },
    {
     "title": "Percentage of http error request group by (grpc_service,grpc_method) ",
     "type": "graph",
     "description": "Percentage of http error request group by (grpc_service,grpc_method)",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{app=\"reviews\",status!=\"200\"}[1m])) by (grpc_service,grpc_method)/sum(rate(http_server_requests_seconds_count{app=\"reviews\"}[1m])) by (grpc_service,grpc_method)* 100.0",
       "legendFormat": "{{grpc_service}}.{{grpc_method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Http server 99%-tile Latency of requests",
   "type": "row",
   "collapsed": true,
   "panels": [
    {
     "title": "Latency of http request group by (grpc_code)",
     "type": "graph",
     "description": "Latency of http request group by (grpc_code)",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "1000 * histogram_quantile(0.98999999999999999,sum(rate(http_server_seconds_bucket{app=\"reviews\"}[1m])) by (grpc_code,le))",
       "legendFormat": "{{grpc_code}}"
      }
     ]
    },
    {
     "title": "Latency of http request group by (instance)",
     "type": "graph",
     "description": "Latency of http request group by (instance)",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "1000 * histogram_quantile(0.98999999999999999,sum(rate(http_server_seconds_bucket{app=\"reviews\"}[1m])) by (instance,le))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Latency of http request group by (grpc_service)",
     "type": "graph",
     "description": "Latency of http request group by (grpc_service)",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "1000 * histogram_quantile(0.98999999999999999,sum(rate(http_server_seconds_bucket{app=\"reviews\"}[1m])) by (grpc_service,le))",
       "legendFormat": "{{grpc_service}}"
      }
     ]
    },
    {
     "title": "Latency of http request group by (grpc_service,grpc_method)",
     "type": "graph",
     "description": "Latency of http request group by (grpc_service,grpc_method)",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "1000 * histogram_quantile(0.98999999999999999,sum(rate(http_server_seconds_bucket{app=\"reviews\"}[1m])) by (grpc_service,grpc_method,le))",
       "legendFormat": "{{grpc_service}}.{{grpc_method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Http server 90%-tile Latency of requests",
   "type": "row",
   "collapsed": true,
   "panels": [
    {
     "title": "Latency of http request group by (grpc_code)",
     "type": "graph",
     "description": "Latency of http request group by (grpc_code)",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "1000 * histogram_quantile(0.90000000000000002,sum(rate(http_server_seconds_bucket{app=\"reviews\"}[1m])) by (grpc_code,le))",
       "legendFormat": "{{grpc_code}}"
      }
     ]
    },
    {
     "title": "Latency of http request group by (instance)",
     "type": "graph",
     "description": "Latency of http request group by (instance)",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "1000 * histogram_quantile(0.90000000000000002,sum(rate(http_server_seconds_bucket{app=\"reviews\"}[1m])) by (instance,le))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Latency of http request group by (grpc_service)",
     "type": "graph",
     "description": "Latency of http request group by (grpc_service)",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "1000 * histogram_quantile(0.90000000000000002,sum(rate(http_server_seconds_bucket{app=\"reviews\"}[1m])) by (grpc_service,le))",
       "legendFormat": "{{grpc_service}}"
      }
     ]
    },
    {
     "title": "Latency of http request group by (grpc_service,grpc_method)",
     "type": "graph",
     "description": "Latency of http request group by (grpc_service,grpc_method)",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "1000 * histogram_quantile(0.90000000000000002,sum(rate(http_server_seconds_bucket{app=\"reviews\"}[1m])) by (grpc_service,grpc_method,le))",
       "legendFormat": "{{grpc_service}}.{{grpc_method}}"
      }
     ]
    }
   ]
  }
 ]
}