// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import models "github.com/sdgmf/go-project-sample/internal/pkg/models"

// DetailsRepository is an autogenerated mock type for the DetailsRepository type
type DetailsRepository struct {
	mock.Mock
}

// Get provides a mock function with given fields: ID
func (_m *DetailsRepository) Get(ID uint64) (*models.Detail, error) {
	ret := _m.Called(ID)

	var r0 *models.Detail
	if rf, ok := ret.Get(0).(func(uint64) *models.Detail); ok {
		r0 = rf(ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Detail)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
