// Code generated by protoc-gen-go. DO NOT EDIT.
// source: details.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetDetailRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDetailRequest) Reset()         { *m = GetDetailRequest{} }
func (m *GetDetailRequest) String() string { return proto.CompactTextString(m) }
func (*GetDetailRequest) ProtoMessage()    {}
func (*GetDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c457112169d4fb2c, []int{0}
}

func (m *GetDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDetailRequest.Unmarshal(m, b)
}
func (m *GetDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDetailRequest.Marshal(b, m, deterministic)
}
func (m *GetDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDetailRequest.Merge(m, src)
}
func (m *GetDetailRequest) XXX_Size() int {
	return xxx_messageInfo_GetDetailRequest.Size(m)
}
func (m *GetDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDetailRequest proto.InternalMessageInfo

func (m *GetDetailRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Detail struct {
	Id                   uint64               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price                float32              `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	CreatedTime          *timestamp.Timestamp `protobuf:"bytes,4,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Detail) Reset()         { *m = Detail{} }
func (m *Detail) String() string { return proto.CompactTextString(m) }
func (*Detail) ProtoMessage()    {}
func (*Detail) Descriptor() ([]byte, []int) {
	return fileDescriptor_c457112169d4fb2c, []int{1}
}

func (m *Detail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Detail.Unmarshal(m, b)
}
func (m *Detail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Detail.Marshal(b, m, deterministic)
}
func (m *Detail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Detail.Merge(m, src)
}
func (m *Detail) XXX_Size() int {
	return xxx_messageInfo_Detail.Size(m)
}
func (m *Detail) XXX_DiscardUnknown() {
	xxx_messageInfo_Detail.DiscardUnknown(m)
}

var xxx_messageInfo_Detail proto.InternalMessageInfo

func (m *Detail) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Detail) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Detail) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Detail) GetCreatedTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedTime
	}
	return nil
}

func init() {
	proto.RegisterType((*GetDetailRequest)(nil), "GetDetailRequest")
	proto.RegisterType((*Detail)(nil), "Detail")
}

func init() { proto.RegisterFile("details.proto", fileDescriptor_c457112169d4fb2c) }

var fileDescriptor_c457112169d4fb2c = []byte{
	// 208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8e, 0x31, 0x4b, 0x03, 0x31,
	0x14, 0x80, 0x49, 0x7a, 0xed, 0xe1, 0x2b, 0x8a, 0x06, 0x87, 0x70, 0x8b, 0xf1, 0xa6, 0x0c, 0x92,
	0x42, 0x5d, 0x9d, 0x44, 0xe8, 0x1e, 0x3a, 0xb9, 0xc5, 0xe6, 0x59, 0x02, 0x8d, 0x39, 0x2f, 0xef,
	0x76, 0x7f, 0xba, 0x90, 0x70, 0x50, 0x6e, 0x4a, 0x3e, 0xde, 0xf7, 0x1e, 0x1f, 0xdc, 0x7a, 0x24,
	0x17, 0x2e, 0xd9, 0x0c, 0x63, 0xa2, 0xd4, 0x3d, 0x9d, 0x53, 0x3a, 0x5f, 0x70, 0x57, 0xe8, 0x6b,
	0xfa, 0xde, 0x51, 0x88, 0x98, 0xc9, 0xc5, 0xa1, 0x0a, 0x7d, 0x0f, 0xf7, 0x07, 0xa4, 0x8f, 0xb2,
	0x64, 0xf1, 0x77, 0xc2, 0x4c, 0xe2, 0x0e, 0x78, 0xf0, 0x92, 0x29, 0xa6, 0x1b, 0xcb, 0x83, 0xef,
	0xff, 0x18, 0x6c, 0xaa, 0xb1, 0x1c, 0x09, 0x01, 0xcd, 0x8f, 0x8b, 0x28, 0xb9, 0x62, 0xfa, 0xc6,
	0x96, 0xbf, 0x78, 0x84, 0xf5, 0x30, 0x86, 0x13, 0xca, 0x95, 0x62, 0x9a, 0xdb, 0x0a, 0xe2, 0x0d,
	0xb6, 0xa7, 0x11, 0x1d, 0xa1, 0x3f, 0x86, 0x88, 0xb2, 0x51, 0x4c, 0x6f, 0xf7, 0x9d, 0xa9, 0x7d,
	0x66, 0xee, 0x33, 0xc7, 0xb9, 0xcf, 0x5e, 0xeb, 0xfb, 0x17, 0x68, 0x6b, 0x41, 0x16, 0xcf, 0xb0,
	0x3a, 0x20, 0x89, 0x07, 0xb3, 0xec, 0xee, 0x5a, 0x53, 0xf9, 0xbd, 0xfd, 0x5c, 0xd7, 0x83, 0x9b,
	0xf2, 0xbc, 0xfe, 0x07, 0x00, 0x00, 0xff, 0xff, 0x92, 0x33, 0x0b, 0x56, 0x16, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DetailsClient is the client API for Details service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DetailsClient interface {
	Get(ctx context.Context, in *GetDetailRequest, opts ...grpc.CallOption) (*Detail, error)
}

type detailsClient struct {
	cc *grpc.ClientConn
}

func NewDetailsClient(cc *grpc.ClientConn) DetailsClient {
	return &detailsClient{cc}
}

func (c *detailsClient) Get(ctx context.Context, in *GetDetailRequest, opts ...grpc.CallOption) (*Detail, error) {
	out := new(Detail)
	err := c.cc.Invoke(ctx, "/Details/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DetailsServer is the server API for Details service.
type DetailsServer interface {
	Get(context.Context, *GetDetailRequest) (*Detail, error)
}

// UnimplementedDetailsServer can be embedded to have forward compatible implementations.
type UnimplementedDetailsServer struct {
}

func (*UnimplementedDetailsServer) Get(ctx context.Context, req *GetDetailRequest) (*Detail, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterDetailsServer(s *grpc.Server, srv DetailsServer) {
	s.RegisterService(&_Details_serviceDesc, srv)
}

func _Details_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DetailsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Details/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DetailsServer).Get(ctx, req.(*GetDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Details_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Details",
	HandlerType: (*DetailsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Details_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "details.proto",
}
