// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ratings.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetRatingRequest struct {
	ProductID            uint64   `protobuf:"varint,1,opt,name=productID,proto3" json:"productID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRatingRequest) Reset()         { *m = GetRatingRequest{} }
func (m *GetRatingRequest) String() string { return proto.CompactTextString(m) }
func (*GetRatingRequest) ProtoMessage()    {}
func (*GetRatingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf07e2fe2aafa921, []int{0}
}

func (m *GetRatingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRatingRequest.Unmarshal(m, b)
}
func (m *GetRatingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRatingRequest.Marshal(b, m, deterministic)
}
func (m *GetRatingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRatingRequest.Merge(m, src)
}
func (m *GetRatingRequest) XXX_Size() int {
	return xxx_messageInfo_GetRatingRequest.Size(m)
}
func (m *GetRatingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRatingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRatingRequest proto.InternalMessageInfo

func (m *GetRatingRequest) GetProductID() uint64 {
	if m != nil {
		return m.ProductID
	}
	return 0
}

type Rating struct {
	Id                   uint64               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductID            uint64               `protobuf:"varint,2,opt,name=productID,proto3" json:"productID,omitempty"`
	Score                uint32               `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	UpdatedTime          *timestamp.Timestamp `protobuf:"bytes,4,opt,name=updatedTime,proto3" json:"updatedTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Rating) Reset()         { *m = Rating{} }
func (m *Rating) String() string { return proto.CompactTextString(m) }
func (*Rating) ProtoMessage()    {}
func (*Rating) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf07e2fe2aafa921, []int{1}
}

func (m *Rating) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rating.Unmarshal(m, b)
}
func (m *Rating) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rating.Marshal(b, m, deterministic)
}
func (m *Rating) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rating.Merge(m, src)
}
func (m *Rating) XXX_Size() int {
	return xxx_messageInfo_Rating.Size(m)
}
func (m *Rating) XXX_DiscardUnknown() {
	xxx_messageInfo_Rating.DiscardUnknown(m)
}

var xxx_messageInfo_Rating proto.InternalMessageInfo

func (m *Rating) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Rating) GetProductID() uint64 {
	if m != nil {
		return m.ProductID
	}
	return 0
}

func (m *Rating) GetScore() uint32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *Rating) GetUpdatedTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedTime
	}
	return nil
}

func init() {
	proto.RegisterType((*GetRatingRequest)(nil), "GetRatingRequest")
	proto.RegisterType((*Rating)(nil), "Rating")
}

func init() { proto.RegisterFile("ratings.proto", fileDescriptor_bf07e2fe2aafa921) }

var fileDescriptor_bf07e2fe2aafa921 = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0x4d, 0x4b, 0xc4, 0x30,
	0x10, 0x86, 0x49, 0xf7, 0xa3, 0x38, 0xcb, 0x8a, 0x06, 0x0f, 0xa5, 0x08, 0xd6, 0x9e, 0x7a, 0x90,
	0x54, 0xea, 0xd5, 0x93, 0x08, 0xc5, 0x6b, 0xe8, 0xc9, 0x5b, 0x6d, 0xc6, 0x12, 0xb0, 0x26, 0x26,
	0x93, 0x3f, 0xe1, 0xaf, 0x16, 0x1a, 0x8b, 0x6e, 0x4f, 0xc3, 0x3b, 0x3c, 0xef, 0xf0, 0x0c, 0x1c,
	0x5d, 0x4f, 0xfa, 0x73, 0xf4, 0xc2, 0x3a, 0x43, 0x26, 0xbf, 0x19, 0x8d, 0x19, 0x3f, 0xb0, 0x9e,
	0xd3, 0x5b, 0x78, 0xaf, 0x49, 0x4f, 0xe8, 0xa9, 0x9f, 0x6c, 0x04, 0xca, 0x7b, 0xb8, 0x68, 0x91,
	0xe4, 0x5c, 0x92, 0xf8, 0x15, 0xd0, 0x13, 0xbf, 0x86, 0x33, 0xeb, 0x8c, 0x0a, 0x03, 0xbd, 0x3c,
	0x67, 0xac, 0x60, 0xd5, 0x56, 0xfe, 0x2d, 0xca, 0x6f, 0x06, 0xfb, 0xc8, 0xf3, 0x73, 0x48, 0xb4,
	0xfa, 0x25, 0x12, 0xad, 0x4e, 0x8b, 0xc9, 0xaa, 0xc8, 0xaf, 0x60, 0xe7, 0x07, 0xe3, 0x30, 0xdb,
	0x14, 0xac, 0x3a, 0xca, 0x18, 0xf8, 0x23, 0x1c, 0x82, 0x55, 0x3d, 0xa1, 0xea, 0xf4, 0x84, 0xd9,
	0xb6, 0x60, 0xd5, 0xa1, 0xc9, 0x45, 0xf4, 0x16, 0x8b, 0xb7, 0xe8, 0x16, 0x6f, 0xf9, 0x1f, 0x6f,
	0xee, 0x20, 0x8d, 0x2e, 0x9e, 0xdf, 0xc2, 0xa6, 0x45, 0xe2, 0x97, 0x62, 0xfd, 0x4f, 0x9e, 0x8a,
	0x98, 0x9f, 0xd2, 0xd7, 0x5d, 0x3c, 0xb8, 0x9f, 0xc7, 0xc3, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xa6, 0xb2, 0x40, 0x95, 0x2e, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RatingsClient is the client API for Ratings service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RatingsClient interface {
	Get(ctx context.Context, in *GetRatingRequest, opts ...grpc.CallOption) (*Rating, error)
}

type ratingsClient struct {
	cc *grpc.ClientConn
}

func NewRatingsClient(cc *grpc.ClientConn) RatingsClient {
	return &ratingsClient{cc}
}

func (c *ratingsClient) Get(ctx context.Context, in *GetRatingRequest, opts ...grpc.CallOption) (*Rating, error) {
	out := new(Rating)
	err := c.cc.Invoke(ctx, "/Ratings/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RatingsServer is the server API for Ratings service.
type RatingsServer interface {
	Get(context.Context, *GetRatingRequest) (*Rating, error)
}

// UnimplementedRatingsServer can be embedded to have forward compatible implementations.
type UnimplementedRatingsServer struct {
}

func (*UnimplementedRatingsServer) Get(ctx context.Context, req *GetRatingRequest) (*Rating, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterRatingsServer(s *grpc.Server, srv RatingsServer) {
	s.RegisterService(&_Ratings_serviceDesc, srv)
}

func _Ratings_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRatingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatingsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Ratings/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatingsServer).Get(ctx, req.(*GetRatingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ratings_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Ratings",
	HandlerType: (*RatingsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Ratings_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ratings.proto",
}
